---
# tasks file for s3cmd-role
- name: Install pip support dependencies
  apt:
      name={{ item }}
      update_cache=yes
  with_items:
      - python-dev
      - python-setuptools

- name: Install pip
  easy_install:
      name=pip

- name: Install s3cmd via pip with specified version
  pip: name=s3cmd version={{s3cmd_version}}
  when: s3cmd_version|default("") != ""

- name: Install latest version of s3cmd via pip
  pip: name=s3cmd
  when: s3cmd_version|default("") == ""

- name: Install configuration file
  template:
    dest: "/root/.s3cfg"
    mode: 0600
    owner: root
    src: "s3cfg.j2"
